train_config:
  hyperparameters:
    hidden_units: 128
    learning_rate: 0.005
    iteration: 100000
  print_model_summary: true
  plot_losses: true
  plot_confusion_matrix: false
  save_model:
    - true
    - 'models/name_classifier.pt'
