train_config:
  hyperparameters:
    hidden_units: 256
    learning_rate: 0.001
    iteration: 1000000
  print_model_summary: true
  plot_losses: true
  plot_confusion_matrix: true
  save_model:
    - true
    - 'models/name_classifier.pt'
